TimSort: fix gallopLeft and gallopRight
3200a76a82 introduced a bug while fixing a compilation error:
        last_offset = offset;
-       var res: usize = undefined;
-       if (@shlWithOverflow(usize, offset, 1, &res)) {
+       var res: usize = undefined;
+       const ov = @shlWithOverflow(offset, @intCast(u6, 1));
+       if (ov[1] == 1) {
            offset = max_offset;
        } else {
            offset = res +| 1;
- the `res` variable should have been removed as new @shlWithOverflow
does not touch it anymore
- last line should be `offset = ov[0] +| 1`, because `ov[0]` holds the
shifted value
- the `+|` can be just `+` as after shifting left the last bit is 0 it
can not overflow when we add 1, it just makes offset an odd number
- when the shift overflows we can just break out from the loop as
`offset < max_offset` can not be true after `offset = max_offset`